name = "open_props"
version = "1.0.0"

description = "Gleam bindings to the open-props design system"
licences = ["MIT"]
repository = { type = "github", user = "dusty-phillips", repo = "open_props_gleam" }
